db:
  hostname: "localhost"
  username: "drayff"
  password: "drayff"
  database: "etta"

diseases:
  example:
    incubation-time: 120 #Время до появления симптомов, в минутах.
    effect-chance: 50 # Шанс на получение негативных эффектов каждые 5 минут, в процентах.
    effects:
      # [айди, уровень, время в секундах]
      - [2, 1, 30]
      - [4, 1, 30]
    transfer-chance: 10 # Шанс на заражение при ударе, в процентах.

#  |  Название эффекта  | ID |
#  |--------------------|----|
#  | SPEED              | 1  |
#  | SLOW               | 2  |
#  | FAST_DIGGING       | 3  |
#  | SLOW_DIGGING       | 4  |
#  | INCREASE_DAMAGE    | 5  |
#  | HEAL               | 6  |
#  | HARM               | 7  |
#  | JUMP               | 8  |
#  | CONFUSION          | 9  |
#  | REGENERATION       | 10 |
#  | DAMAGE_RESISTANCE  | 11 |
#  | FIRE_RESISTANCE    | 12 |
#  | WATER_BREATHING    | 13 |
#  | INVISIBILITY       | 14 |
#  | BLINDNESS          | 15 |
#  | NIGHT_VISION       | 16 |
#  | HUNGER             | 17 |
#  | WEAKNESS           | 18 |
#  | POISON             | 19 |
#  | WITHER             | 20 |
#  | HEALTH_BOOST       | 21 |
#  | ABSORPTION         | 22 |
#  | SATURATION         | 23 |
#  | GLOWING            | 24 |
#  | LEVITATION         | 25 |
#  | LUCK               | 26 |
#  | UNLUCK             | 27 |
#  | SLOW_FALLING       | 28 |
#  | CONDUIT_POWER      | 29 |
#  | DOLPHINS_GRACE     | 30 |
#  | BAD_OMEN           | 31 |
#  | HERO_OF_THE_VILLAGE| 32 |
#  | DARKNESS           | 33 |